name: Build and Push Docker image, Trufflehog, Semgrep and Snyk scans + Discord notifications

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Discord-Begin:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Notification start
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: ${{ github.repository }}
          avatar-url: https://gravatar.com/avatar/be5d3fe06696117c467f199ddb4f1aed?s=400&d=robohash&r=g
          embed-title: "Security Pipeline jobs are starting..."
          embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          embed-description: "[Action details ${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          embed-author-name: "${{ github.triggering_actor }}"

  trufflehog_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: TruffleHog Action
        uses: trufflesecurity/trufflehog@v3.0.1
        with:
          scanArguments: "--format sarif --output trufflehog-report.sarif"
      - name: Upload SARIF report
        uses: actions/upload-artifact@v2
        with:
          name: trufflehog-sarif-report
          path: trufflehog-report.sarif
  

  semgrep_scan:
    runs-on: ubuntu-latest
    needs: trufflehog_scan
    steps:
      - name: Run Semgrep
        run: |
          docker run --rm -v ${{ github.workspace }}:/src returntocorp/semgrep semgrep \
          --config="p/r2c-ci" \
          --sarif --output /src/semgrep.sarif \
          /src
      - name: Upload Semgrep SARIF report
        uses: actions/upload-artifact@v2
        with:
          name: semgrep-sarif-report
          path: semgrep.sarif
      - name: Discord Notification for Semgrep Scan Completion
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: ${{ github.repository }}
          avatar-url: https://gravatar.com/avatar/be5d3fe06696117c467f199ddb4f1aed?s=400&d=robohash&r=g
          embed-title: "SAST-Semgrep completed!"
          embed-description: "[Action details ${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})\nUploaded: [semgrep-sarif-report.sarif](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"

  snyk_scan:
    runs-on: ubuntu-latest
    needs: semgrep_scan
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check Docker image for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/docker@master
        with:
          image: manwinderj/nodegoat:latest
          args: --file=Dockerfile --sarif-file-output=snyk.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Upload SARIF report as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: snyk.sarif
          path: snyk.sarif
      - name: Discord Notification for Snyk Scan Completion
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: ${{ github.repository }}
          avatar-url: https://gravatar.com/avatar/be5d3fe06696117c467f199ddb4f1aed?s=400&d=robohash&r=g
          embed-title: "SCA-Snyk completed!"
          embed-description: "[Action details ${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})\nUploaded: [snyk.sarif](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"

  build:
    runs-on: ubuntu-latest
    needs: snyk_scan
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: manwinderj/nodegoat:latest
      - name: Discord Notification for Pipeline Completion
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: ${{ github.repository }}
          avatar-url: https://gravatar.com/avatar/be5d3fe06696117c467f199ddb4f1aed?s=400&d=robohash&r=g
          embed-title: "Security Pipeline jobs completed!"
          embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          embed-description: |
            [Action details ${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          embed-author-name: "${{ github.triggering_actor }}"
          
