name: Build and Push Docker image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: manwinderj/nodegoat:latest 

  trufflehog_scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: TruffleHog Action
        uses: trufflesecurity/trufflehog@v3.0.1
        with:
          scanArguments: "--format sarif --output trufflehog-report.sarif"
        
      - name: Upload SARIF report
        uses: actions/upload-artifact@v2
        with:
          name: trufflehog-sarif-report
          path: trufflehog-report.sarif

  semgrep_scan:
    runs-on: ubuntu-latest
    needs: trufflehog_scan
    steps:
      - name: Run Semgrep
        uses: docker://returntocorp/semgrep
        with:
          args: "--config='p/r2c-ci' --sarif --output /github/workspace/semgrep.sarif /github/workspace"

      - name: Upload Semgrep SARIF report
        uses: actions/upload-artifact@v2
        with:
          name: semgrep-sarif-report
          path: /github/workspace/semgrep.sarif

  snyk_scan:
    runs-on: ubuntu-latest
    needs: [trufflehog_scan, semgrep_scan]
    steps:
      - uses: actions/checkout@v2
      
      - name: Build a Docker image
        run: docker build -t manwinderj/nodegoat:latest
      
      - name: Run Snyk to check Docker image for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/docker@master
        with:
          image: manwinderj/nodegoat:latest
          args: --file=Dockerfile

      - name: Upload SARIF report as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: snyk.sarif
          path: snyk.sarif
