name: Build and Push Docker image

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: manwinderj/nodegoat:latest
    
    - name: Run Semgrep
      run: |
          docker run --rm -v ${{ github.workspace }}:/src returntocorp/semgrep \
          --config="p/r2c-ci" \
          --sarif --output semgrep.sarif \
          /src
    - name: Upload Semgrep SARIF report
      uses: actions/upload-artifact@v2
      with:
          name: semgrep-sarif-report
          path: semgrep.sarif

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: manwinderj/nodegoat:latest
        args: --file=Dockerfile --sarif-file-output=snyk.sarif
    - name: Upload Snyk SARIF report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: snyk.sarif

