name: Build docker image and deploy to wmd docker servers

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    name: "Deploy to ITAS WMD server"
    runs-on: itas276-manwinder

    steps:
      - name: Copy source code files
        uses: actions/checkout@master

      - name: Test files are visible
        run: |
          whoami
          ls -lah

      - name: Build Docker Images
        run: docker-compose build

      - name: Run the application
        run: docker-compose up -d
